### ISSUE TITLE
GATK4, CNV and SV

### ISSUE THREAD

**Issue by jielab** [gencorefacility/variant-calling-pipeline#1]
Hi, there:

Do you have an updated pipeline.sh using GATK4? Also, do you have the scripts for calling CNV and SV?

Thank you very much & Happy Holiday!

Jie

--
Jie Huang, MD PhD
Harvard Medical School

**Comment by mohammedkhalfan** [comment]
Hello Jie,

Unfortunately I have not updated the pipeline using GATK4, and don't currently have a pipeline for CNVs or SVs. 

Best,
Mohammed
